### ISSUE TITLE
Renderer's properties aren't merged correctly in render_system_drawer

### ISSUE THREAD

**Issue by madwareru** [enduro2d/enduro2d#70]
### Description of a problem
Nothing happens when you use custom uniforms in a shader and trying to update them somewhere.

### Steps to reproduce
1. Create a shader with a custom uniform, say a `uniform float u_time;`
2. Use it to do some animations
3. Create a system which updates renderer's property `u_time` with a game time
4. Observe no animation

### Expected behaviour
Animation executed correctly

### Solution
[Link to a problem place](https://github.com/enduro2d/enduro2d/blob/16da91496cb157978164d9f6687d363c58ac54d5/sources/enduro2d/high/systems/render_system_impl/render_system_drawer.cpp#L96)

In a function `drawer::context::draw`
Instead of
```
property_cache_
    .property("u_matrix_m", node->world_matrix())
    .merge(internal_properties_);
```
there should be
```
property_cache_
    .property("u_matrix_m", node->world_matrix())
    .merge(node_r.properties()) // <-- aha!
    .merge(internal_properties_);
```

**Comment by BlackMATov** [comment]
already fixed in master :)
